/// ap_slot_connected(slot_data)
{
    show_debug_message("AP: Slot connected: " + string(argument0));
    global.AP_connected = true;
    global.ap_boss_item_backfill_done = false;
    global.ap_ever_connected = true;
    ap_apply_slot_data(argument0);
    if (global.ap_created_manifest_error || !global.ap_created_manifest_ready)
    {
        global.AP_connected = false;
        global.AP_last_error = "This slot was generated by an unsupported old ZALiA apworld.";
        show_debug_message("AP: Disconnecting: " + global.AP_last_error);
        apclient_disconnect();
        show_message(global.AP_last_error + "#Generate a new multiworld with the current apworld.");
        exit;
    }

    // Load srv's confirmed checked locations.
    if (!variable_global_exists("ap_checked_ids"))
        global.ap_checked_ids = ds_list_create();
    else
        ds_list_clear(global.ap_checked_ids);

    // apclient_get_checked_locations() returns a GML struct string
    var _server_checked = apclient_get_checked_locations();
    var _chk_key = "global.ap_checked_locations[";
    var _chk_klen = string_length(_chk_key);
    var _chk_raw = _server_checked;
    var _chk_added = 0;
    // Safety cap against malformed input.
    var _chk_cap = ds_map_size(global.ap_created_location_ids) + 16;
    if (_chk_cap < 200) _chk_cap = 200;
    repeat(_chk_cap)
    {
        var _chk_p = string_pos(_chk_key, _chk_raw);
        if (_chk_p == 0) break;
        _chk_raw = string_delete(_chk_raw, 1, _chk_p + _chk_klen - 1);
        // _chk_raw starts at the index digit(s)
        var _chk_eq = string_pos("]=", _chk_raw);
        if (_chk_eq == 0) break;
        // Remove index digits + "]="
        _chk_raw = string_delete(_chk_raw, 1, _chk_eq + 1);
        // _chk_raw now starts at the value
        var _chk_semi = string_pos(";", _chk_raw);
        if (_chk_semi == 0) break;
        var _chk_val = real(string_copy(_chk_raw, 1, _chk_semi - 1));
        _chk_raw = string_delete(_chk_raw, 1, _chk_semi);
        if (_chk_val > 0 && ds_list_find_index(global.ap_checked_ids, _chk_val) == -1)
        {
            ds_list_add(global.ap_checked_ids, _chk_val);
            _chk_added++;
        }
    }
    show_debug_message("AP: Loaded " + string(ds_list_size(global.ap_checked_ids)) + " checked locations (" + string(_chk_added) + " new from server)");

    // Refresh overworld checkmark data with srv-accurate
    ap_refresh_overworld_marks();

    // Scout all ZALiA locations to cache
    ds_map_clear(global.ap_scouted_flags);
    ds_map_clear(global.ap_scouted_players);
    ds_map_clear(global.ap_scouted_item_ids);
    ds_map_clear(global.ap_scouted_sprites);
    ds_map_clear(global.ap_scouted_item_types);
    // Scout every real location for this slot.
    var _scout_ids = "[";
    var _loc_count = 0;

    // Scout precisely the authoritative created-location set.
    var _created_id = ds_map_find_first(global.ap_created_location_ids);
    while (!is_undefined(_created_id))
    {
        if (_loc_count > 0) _scout_ids += ",";
        _scout_ids += string(_created_id);
        _loc_count++;
        _created_id = ds_map_find_next(global.ap_created_location_ids, _created_id);
    }
    _scout_ids += "]";
    apclient_location_scouts(_scout_ids, 0);
    show_debug_message("AP: Scouting " + string(_loc_count) + " locations");

    // Store local player number for cross-world
    global.ap_local_player = apclient_get_player_number();

    // Read DeathLink setting from slot_data
    var _dl = ds_map_find_value(global.ap_slot_data, "death_link");
    global.ap_deathlink_enabled = (!is_undefined(_dl) && _dl == 1);
    if (global.ap_deathlink_enabled)
    {
        // Set DeathLink tag at srv
        apclient_connect_update('["DeathLink"]');
        show_debug_message("AP: DeathLink enabled");
    }
    else
        show_debug_message("AP: DeathLink disabled");
}
